language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: XDEBUG_OFF="yes"

before_script:
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;

script:
  - composer update
  - chmod +x ./webserver.sh
  - curl -S http://localhost:8888
